apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
    auction: static
spec:
  selector:
    matchLabels:
      {{- include "charts.selectorLabels" . | nindent 6 }}
      auction: static
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "charts.selectorLabels" . | nindent 8 }}
        auction: static
    spec:
      containers:
        - name: {{ .Chart.Name }}.static
          tty: true
          image: "{{ .Values.image.repository }}:STATIC_{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # command:
          #   - bash
      imagePullSecrets:
       - name: {{ .Values.imagePullSecrets }}
