name: build and deploy test environment on pr

on:
  pull_request:
    branches:
    - main

  push:
    branches:
    - build_test_deploy

jobs:
  
  build_and_test:
    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v2

      - name: Set image tag
        run: |
          SHORT_SHA=$(git describe --always)
          echo "ghcr.io/internetee/auction_center:RC_$SHORT_SHA" > TAG
          echo "ghcr.io/internetee/auction_center:RC_STATIC_$SHORT_SHA" > STATIC_TAG

      - name: Set config files for build
        run: |
          cp config/database.yml.sample config/database.yml
          ls -l config/

      - name: Build image
        run: |
          docker build -t $(cat TAG) -f Dockerfile.generic .

      - name: Build proxy image with static content
        run: |
          docker create -ti --name rails $(cat TAG) bash
          docker cp rails:/opt/webapps/app/public/ ./public/
          docker build -t $(cat STATIC_TAG) -f Dockerfile.generic-static .

      - name: Push Docker image to gh container registry
        env:
          PASSWORD: ${{ secrets.GHCR }}
        run: |
          echo $PASSWORD | docker login ghcr.io -u eisbot --password-stdin
          docker push $(cat TAG)
          docker push $(cat STATIC_TAG)
