name: build and deploy staging

on:

  pull_request:
    branches:
    - master

jobs:
  
  build:
    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v2

      - name: Set image tag
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c 1-7) #pr-s test commit of merged state
          echo "TAG=ghcr.io/internetee/auction_center:RC-$SHORT_SHA" >> $GITHUB_ENV
          echo "STATIC_TAG=ghcr.io/internetee/auction_center:STATIC_RC-$SHORT_SHA" >> $GITHUB_ENV
          echo "SHORT_TAG=RC-$SHORT_SHA" >> $GITHUB_ENV

      - name: Set config files for build
        run: |
          cp config/customization.yml.sample config/customization.yml
          cp config/database.yml.sample config/database.yml
          ls -l config/        

      - name: Build rails image
        run: |
          docker build -t $TAG -f Dockerfile.generic .

      - name: Build static content image
        env:
          PASSWORD: ${{ secrets.GHCR }}
        run: |
          echo $PASSWORD | docker login ghcr.io -u eisbot --password-stdin
          docker create -ti --name rails $TAG bash
          docker cp rails:/opt/webapps/app/public/ ./public/
          docker build -t $STATIC_TAG -f Dockerfile.generic-static .

      - name: Push Docker images to gh container registry
        run: |
          docker push $TAG
          docker push $STATIC_TAG

      - name: Get pull request reference number
        run: |
          OIFS=$IFS
          IFS='/'
          read -a parts <<< "$GITHUB_REF"
          IFS=OIFS
          echo "PR_REF=${parts[2]}" >> $GITHUB_ENV

      - name: Get repo name
        run: |
          OIFS=$IFS
          IFS='/'
          read -a parts <<< "$GITHUB_REPOSITORY"
          IFS=OIFS
          echo "REPO=${parts[1]}" >> $GITHUB_ENV

      - name: Set deploy config
        env:
          OVPN: ${{ secrets.OVPN }}
          VPN_PWD: ${{ secrets.VPN_PWD }}
          P12: ${{ secrets.P12 }}
          K_CONFIG: ${{ secrets.KUBE_CONFIG }}
          SSH_KEY: ${{ secrets.EISBOT_SSH_KEY }}
        run: |
          echo $VPN_PWD | base64 -di > client.pwd
          chmod 0600 client.pwd
          echo $OVPN | base64 -di >  config.ovpn
          echo $P12 | base64 -di > cert.p12
          mkdir -p ~/.ssh
          echo $SSH_KEY | base64 -di > ~/.ssh/key
          chmod 0600 ~/.ssh/key
          mkdir -p $REPO/$PR_REF
          cd $REPO/$PR_REF
          echo "$SHORT_SHA" > TAG
          echo $K_CONFIG | base64 -di > kubeconfig
          chmod 0600 kubeconfig

      - name: Install Open VPN
        run: sudo apt-get install openvpn

      - name: Deploy from remote server
        timeout-minutes: 5
        run: |
          sudo openvpn --config config.ovpn --askpass client.pwd --auth-nocache --daemon&
          sleep 15
          ping -c 1 192.168.99.12
          eval `ssh-agent`
          touch ~/.ssh/known_hosts   
          ssh-add ~/.ssh/key
          ssh-keyscan 192.168.99.12 > ~/.ssh/known_hosts
          rsync -av "$REPO" runner@192.168.99.12:/home/runner/
          ssh -T runner@192.168.99.12 << EOSSH
          bash
          cd "$REPO"/"$PR_REF"
          export KUBECONFIG=./kubeconfig
          helm repo add eisrepo https://internetee.github.io/helm-charts/
          helm repo update
          helm upgrade --install auction-st-"$PR_REF" --set image.tag="$SHORT_TAG",reference="$PR_REF" eisrepo/auction -n auction-staging
          rm kubeconfig
          EOSSH
